# Server configurations
server:
  port: 1000

# Database configurations (Modify according to your database setup)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patient_db?useSSL=false
    username: root
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true